### ISSUE TITLE
[DataCap Application] <Xinjiang Nongyuan Jiaye Agricultural Investment Co., Ltd> - <agricultural data> 

### ISSUE THREAD

**Issue by Brady168** [Lind111/EF#9] opened 2024-03-30 03:02 UTC
### Version

1

### DataCap Applicant

Brady

### Project ID

1

### Data Owner Name

Xinjiang Nongyuan Jiaye Agricultural Investment Co., Ltd

### Data Owner Country/Region

China

### Data Owner Industry

Resources, Agriculture & Fisheries

### Website

N/A

### Social Media Handle

Email:2281895919@qq.com

### Social Media Type

Other

### What is your role related to the dataset

Dataset Owner

### Total amount of DataCap being requested

8PiB

### Unit for total amount of DataCap being requested

PiB

### Expected size of single dataset (one copy)

1.5PiB

### Unit for expected size of single dataset

PiB

### Number of replicas to store

11

### Weekly allocation of DataCap requested

1PiB

### Unit for weekly allocation of DataCap requested

PiB

### On-chain address for first allocation

f1txfwjexmp4gp3dqdglgc3i7qacnyseocs4cecky

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Xinjiang Nongyuan Jiaye Agricultural Investment Co., Ltd. was established on July 26, 2016, and its registered address is 604, Floor 6, Jiangnan Senior Apartment, Saiwai, No. 1096, Karamay West Street, Saybag District, Ürümqi, Xinjiang. Its legal representative is Li Zhifeng. The business scope includes agricultural technology extension services, crop planting, agricultural services, Agricultural science research and experimental development, agricultural tourism, import and export of goods and technology, online trade agents, software and information technology services, Information technology consulting consulting services, vocational skills training, poultry breeding; Sales: agricultural products, livestock products, fresh aquatic products, daily necessities, vegetables and fruits; Wholesale and retail: pre packaged food and bulk food.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Video files include displays of farmland, various plants and animals, research data and images, etc
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
Our technical department has tested and mastered the packaging data and issued the order command, using the branch packaging data under singularity, and using the boost tool to issue the order.
```

### If you are not preparing the data, who will prepare the data?  (Provide name and business)

```text
Our own technical department prepares the data
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
N/A
```

### Please share a sample of the data

```text
https://drive.google.com/drive/folders/1nDKibmicmL4-c7YCEWwACMwA_SxrtCTE?usp=drive_link
https://drive.google.com/drive/folders/1eiaYIB4X-yG3zRZtaKElF-iLoC1VtU7j?usp=drive_link
https://drive.google.com/drive/folders/1mqyXgA1P0dfb8r9rhli3T-lL2676SJXz?usp=drive_link
https://drive.google.com/drive/folders/1V90RWTvFyZRA8hLshPse8mgXPNocQtm7?usp=drive_link
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How did you find your storage providers

Slack, Partners, Others

### If you answered "Others" in the previous question, what is the tool or platform you used

```text
Other Social Software in China
```

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f02770938 South Korea
f02820008 Hong Kong
f02237010 Tokyo
f02093396 Singapore
f02259777 Singapore
f01888808 Romania
f02866666  Tokyo
f03144777  Tokyo
f02820000  GuangZhou
f02639655  GuangZhou
f02588263  Hong Kong
f02362412 California
f02639492 California
f03166666 Hongkong
f03166668 Hongkong
f02368946 Huhehaote
f02822222 Hong Kong
```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Lind111** [comment] 2024-03-30 03:35
First, please click on https://github.com/filecoin-project/notary-governance/issues/1056#issuecomment-1890621214 to view my allocation rules

**Comment by Lind111** [comment] 2024-03-30 03:40
Could you send an email with business license to qq248245620@gmail.com with your official domain in order to confirm your identity?The email should include the miner ID, the business entity, a list of sps locations you will be working with

**Comment by Brady168** [comment] 2024-03-30 05:50
> First, please click on [filecoin-project/notary-governance#1056 (comment)](https://github.com/filecoin-project/notary-governance/issues/1056#issuecomment-1890621214) to view my allocation rules

Read in full

**Comment by Brady168** [comment] 2024-03-30 05:50
> Could you send an email with business license to [qq248245620@gmail.com](mailto:qq248245620@gmail.com) with your official domain in order to confirm your identity?The email should include the miner ID, the business entity, a list of sps locations you will be working with

sent

**Comment by Lind111** [comment] 2024-03-30 05:53
![image](https://github.com/Lind111/EF/assets/130743579/e3c0adf3-e025-4666-a4b9-5594ece2ec63)
Confirmed and published SPs related information：
f02770938 guan South Korea
f02820008 zhangx Hong Kong
f02237010 Li Tokyo
f02093396 Lingchao Xu Singapore
f02259777 Lingchao Xu Singapore
f01888808 郑建林 Romania

**Comment by Lind111** [comment] 2024-03-30 05:55
Have you or sps prepared enough token for sector pledge?

**Comment by Brady168** [comment] 2024-03-30 05:56
> Have you or sps prepared enough token for sector pledge?

It's all ready to go. Some of the data is still being transferred.

**Comment by Brady168** [comment] 2024-03-30 06:14
thank you

**Comment by Brady168** [comment] 2024-04-02 05:01
> ![image](https://private-user-images.githubusercontent.com/130743579/318171400-e3c0adf3-e025-4666-a4b9-5594ece2ec63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMzQyNDAsIm5iZiI6MTcxMjAzMzk0MCwicGF0aCI6Ii8xMzA3NDM1NzkvMzE4MTcxNDAwLWUzYzBhZGYzLWUwMjUtNDY2Ni1hNGI5LTU1OTRlY2UyZWM2My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMlQwNDU5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDgwMTQzYTAyZWJhMTA5MWVjM2Y2MjJlNGY4MWJlYzdkNGQ0N2RkZDM0Zjg1YTFmODUzODdiMmEzZWM5OTUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RmQLMxB3rDotSAWJVGWnpGzz8j7CXlk2SIP_gWsB8cA) Confirmed and published SPs related information： f02770938 guan South Korea f02820008 zhangx Hong Kong f02237010 Li Tokyo f02093396 Lingchao Xu Singapore f02259777 Lingchao Xu Singapore f01888808 郑建林 Romania

add
f03034045    luna  Tokyo

**Comment by Lind111** [comment] 2024-04-02 06:25
Checking to see that the currently sealed SPs don't match what you claim, only a few work for you, can you explain that?
![image](https://github.com/Lind111/EF/assets/130743579/43248425-c248-485e-87de-e56bdfd5bd8d)

Confirmed and published SPs related information：
f02770938 guan South Korea
f02820008 zhangx Hong Kong
f02237010 Li Tokyo
f02093396 Lingchao Xu Singapore
f02259777 Lingchao Xu Singapore
f01888808 郑建林 Romania

**Comment by Lind111** [comment] 2024-04-02 06:36
f02820008  Hong Kong /ip4/119.8.115.16/tcp/21980      √
f02770938  South Korea /ip4/103.1.33.179/tcp/34120  ×  This ip address is located in Hong Kong, which is inconsistent with the statement, can you explain?
f02237010  Tokyo /ip4/123.108.70.6/tcp/59660   √

**Comment by Brady168** [comment] 2024-04-02 06:51
> Checking to see that the currently sealed SPs don't match what you claim, only a few work for you, can you explain that? ![image](https://private-user-images.githubusercontent.com/130743579/318665467-43248425-c248-485e-87de-e56bdfd5bd8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNDA4ODgsIm5iZiI6MTcxMjA0MDU4OCwicGF0aCI6Ii8xMzA3NDM1NzkvMzE4NjY1NDY3LTQzMjQ4NDI1LWMyNDgtNDg1ZS04N2RlLWU1NmJkZmQ1YmQ4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMlQwNjQ5NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMjMwOWUyMmFkMTk0ODc2MDllNDc0ZjZmZTVmODRhMmNlY2ZkN2E3MjVkZWJlZDYwNGFjNTFjNTI5ZjEwM2ZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UuUe2bqbD6HXqdjkrC0V7taSdHDUjfrEF3ZeozYg-34)
> 
> Confirmed and published SPs related information： f02770938 guan South Korea f02820008 zhangx Hong Kong f02237010 Li Tokyo f02093396 Lingchao Xu Singapore f02259777 Lingchao Xu Singapore f01888808 郑建林 Romania

Located in the pre-phase, some sp's are still transmitting data, a new cooperating sp will be added Information is as follows
f02816666 Huhehaote

**Comment by Brady168** [comment] 2024-04-02 06:53
> f02820008 Hong Kong /ip4/119.8.115.16/tcp/21980 √ f02770938 South Korea /ip4/103.1.33.179/tcp/34120 × This ip address is located in Hong Kong, which is inconsistent with the statement, can you explain? f02237010 Tokyo /ip4/123.108.70.6/tcp/59660 √

Just asked their techs and what they explained is that the client is from Korea but their machine is hosted in Hong Kong, so it's a Hong Kong ip

**Comment by Lind111** [comment] 2024-04-02 06:55
> > f02820008 Hong Kong /ip4/119.8.115.16/tcp/21980 √ f02770938 South Korea /ip4/103.1.33.179/tcp/34120 × This ip address is located in Hong Kong, which is inconsistent with the statement, can you explain? f02237010 Tokyo /ip4/123.108.70.6/tcp/59660 √
> 
> Just asked their techs and what they explained is that the client is from Korea but their machine is hosted in Hong Kong, so it's a Hong Kong ip

Please provide proof of geographical location information, which can be sent to [qq248245620@gmail.com](mailto:qq248245620@gmail.com)

**Comment by Lind111** [comment] 2024-04-02 07:06
Confirmed

**Comment by Lind111** [comment] 2024-04-02 07:07
A second allocation will be made

**Comment by Brady168** [comment] 2024-04-06 15:08
Request for third round of allocation

**Comment by Lind111** [comment] 2024-04-06 15:17
Receive

**Comment by Lind111** [comment] 2024-04-06 15:19
> Number of replicas to store
> 6

You claim to store 6 copies, but currently there are only 4. Can you explain your plan?
![image](https://github.com/Lind111/EF/assets/130743579/d72bc3c8-fd32-4e79-b4f2-970ef11981e7)

**Comment by Lind111** [comment] 2024-04-06 15:20
Synchronizing data retrieval for verification

**Comment by Brady168** [comment] 2024-04-07 01:39
> > Number of replicas to store
> > 6
> 
> You claim to store 6 copies, but currently there are only 4. Can you explain your plan? ![image](https://private-user-images.githubusercontent.com/130743579/320215238-d72bc3c8-fd32-4e79-b4f2-970ef11981e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NTQwMTcsIm5iZiI6MTcxMjQ1MzcxNywicGF0aCI6Ii8xMzA3NDM1NzkvMzIwMjE1MjM4LWQ3MmJjM2M4LWZkMzItNGU3OS1iNGYyLTk3MGVmMTE5ODFlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QwMTM1MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYjQzMGFlMWYwODljNjNhOTBmMGQxMzBkZDc2ZTQ5ZDUxOGY4ZWI5MzQwOGY0Y2ZiN2Y4ZGNkMmI0ZWU3YWMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.z_tGksPyGzqjvZqVHgE3mB7HRB5SGNBA4d8kvaSemQI)

I'm reaching out to more SP's, there is now assured word of being able to work together and I'm sure I'll be able to get on board soon, the existing published section is still transmitting data and I'm sure we'll reach 6 copies soon!

**Comment by Lind111** [comment] 2024-04-07 01:52
![image](https://github.com/Lind111/EF/assets/130743579/281a6dd0-ef72-451c-8395-eac5d141e6f6)
Reconfirm that a single SP does not exceed 30%

**Comment by Brady168** [comment] 2024-04-07 01:57
I'm actively adjusting the data distribution, I believe it will be improved by the addition of new SPs in the back, thanks for the heads up!

**Comment by Lind111** [comment] 2024-04-07 01:59
> Reconfirm that a single SP has exceeded 30%, please use datacap reasonably

Checking if the retrieved data is consistent

**Comment by Lind111** [comment] 2024-04-07 02:24
![image](https://github.com/Lind111/EF/assets/130743579/35447e87-53a6-45aa-8433-aa75bc5dede6)
Retrieve baga6ea4seaqemiesc7kl4tv6vtwmi2srzemplinnu3mjhouko3yx4tsybksycci
Confirm consistency with [sample data](https://drive.google.com/drive/folders/1u8kvex1kcq9ntkCtpOBpXp_RGUk1yfYA), both belong to agriculture

**Comment by Lind111** [comment] 2024-04-07 02:25
The next round of allocation will be initiated

**Comment by Lind111** [comment] 2024-04-07 02:34
2800Tib has been allocated, and there are still 5200Tib remaining

**Comment by Brady168** [comment] 2024-04-07 10:46
A new cooperating sp will be added Information is as follows
f02814682 Guangzhou

**Comment by Brady168** [comment] 2024-04-09 05:48
A new cooperating sp will be added Information is as follows
f02215209  California

**Comment by Brady168** [comment] 2024-04-11 08:22
A new cooperating sp will be added Information is as follows
f02062851 California

**Comment by Lind111** [comment] 2024-04-16 01:01
checker:manualTrigger

**Comment by filecoin-watchdog** [comment] 2024-05-10 12:18
checker:manualTrigger

**Comment by Lind111** [comment] 2024-05-16 06:39
checker:manualTrigger

**Comment by Lind111** [comment] 2024-06-26 07:59
checker:manualTrigger

**Comment by Brady168** [comment] 2024-07-01 01:47
The following new partners were found
| ID | City Name  |
|-----------|------------|
| f02866666 | Tokyo      |
| f03144777 | Tokyo      |
| f02820000 | GuangZhou  |
| f02639655 | GuangZhou  |
| f02588263 | Hong Kong  |

**Comment by Lind111** [comment] 2024-07-01 02:14
checker:manualTrigger

**Comment by Lind111** [comment] 2024-07-01 02:50
> The following new partners were found
> 
> ID	City Name
> f02866666	Tokyo
> f03144777	Tokyo
> f02820000	GuangZhou
> f02639655	GuangZhou
> f02588263	Hong Kong


Looks like the DataCap Application hasn't had any data updates for over 2 months, glad you found a new partner!

**Comment by Lind111** [comment] 2024-07-01 02:57
f02866666 Tokyo
Multiaddrs:	/ip4/103.160.100.187/tcp/6666
f03144777 Tokyo
Multiaddrs:	/ip4/103.160.100.187/tcp/44777
![image](https://github.com/Lind111/EF/assets/130743579/3f100e00-7ac3-4b54-bca8-f800da7ea6a5)
f02820000 GuangZhou
Multiaddrs:	/ip4/14.215.165.46/tcp/15890
![image](https://github.com/Lind111/EF/assets/130743579/b83a7959-544f-4014-b657-d997894dfda6)

f02639655 GuangZhou
Multiaddrs:	/ip4/113.96.22.206/tcp/6789
![image](https://github.com/Lind111/EF/assets/130743579/82de432e-cb25-4105-8f8e-4154f03fd3bb)

f02588263 Hong Kong
Multiaddrs:	/ip4/103.201.24.43/tcp/5232
![image](https://github.com/Lind111/EF/assets/130743579/e57c368a-3823-48c7-aab7-e34fc67f9e95)

**Comment by Lind111** [comment] 2024-07-01 02:57
Confirmed. Start your work.

**Comment by Lind111** [comment] 2024-07-03 02:35
checker:manualTrigger

**Comment by Brady168** [comment] 2024-07-05 01:25
Request for next round of distribution

**Comment by Brady168** [comment] 2024-07-05 01:29
checker:manualTrigger

**Comment by Lind111** [comment] 2024-07-05 07:43
checker:manualTrigger

**Comment by Lind111** [comment] 2024-07-05 07:48
Great, it looks like the newly added SPs all support spark retrieval!

**Comment by Lind111** [comment] 2024-07-05 07:56
Due to the datacap shortage, I assigned the last 700TiB to that path and will assign it again when the datacap is replenished

**Comment by Lind111** [comment] 2024-07-08 08:34
checker:manualTrigger

**Comment by Lind111** [comment] 2024-07-11 02:48
checker:manualTrigger

**Comment by Lind111** [comment] 2024-07-15 10:28
checker:manualTrigger

**Comment by Lind111** [comment] 2024-07-23 06:43
checker:manualTrigger

**Comment by Lind111** [comment] 2024-08-05 09:25
checker:manualTrigger

**Comment by Lind111** [comment] 2024-08-16 03:31
checker:manualTrigger

**Comment by Lind111** [comment] 2024-08-16 19:23
![image](https://github.com/user-attachments/assets/63bbcfbb-63e1-47d3-b3f8-187aa96ce587)
Two undisclosed SPs appeared, can you explain that?

**Comment by Brady168** [comment] 2024-08-19 09:32
> ![image](https://private-user-images.githubusercontent.com/130743579/358694313-63bbcfbb-63e1-47d3-b3f8-187aa96ce587.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNjAxNDksIm5iZiI6MTcyNDA1OTg0OSwicGF0aCI6Ii8xMzA3NDM1NzkvMzU4Njk0MzEzLTYzYmJjZmJiLTYzZTEtNDdkMy1iM2Y4LTE4N2FhOTZjZTU4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOVQwOTMwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGQ5YjkxYWZjMDlhZjZmY2QxZmJlNGU3OGY1Zjk4ZWI4NzI0OWZlZjhkY2ZlMWI2YzA5ZmIzNTg4YWNmODg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aIIvm-Gw8QDYch7FSHFT4beC4u5L-oG4r31qZ6Jfvv8) Two undisclosed SPs appeared, can you explain that?

sorry，Forgot to put it in the comments ahead of time，New SPs found to work with after the stfil incident
f03175168 Shenzhen
f03175111 Shenzhen

**Comment by Lind111** [comment] 2024-08-20 02:59
checker:manualTrigger

**Comment by Lind111** [comment] 2024-09-18 06:56
checker:manualTrigger

**Comment by Lind111** [comment] 2024-09-24 03:10
checker:manualTrigger

**Comment by Brady168** [comment] 2024-09-24 03:25
Re-add the following SPs 
f02362412 California
f02639492 California
f03166666 Hongkong
f03166668 Hongkong
f02368946 Huhehaote
f02822222 Hong Kong

**Comment by Lind111** [comment] 2024-09-24 03:38
> Re-add the following SPs f02362412 California f02639492 California f03166666 Hongkong f03166668 Hongkong f02368946 Huhehaote f02822222 Hong Kong

Please send documentation of the geographic location of these SPs to [qq248245620@gmail.com](mailto:qq248245620@gmail.com)

**Comment by Lind111** [comment] 2024-09-24 07:08
confirmed

**Comment by Lind111** [comment] 2024-09-24 07:13
![image](https://github.com/user-attachments/assets/42565cd8-f1b3-4d9a-99be-956ac34d0159)
The client's last deal was queried on August 11, and since the latest CID report is faulty, That's why I referenced[ the August 20th CID report ](https://github.com/Lind111/EF/issues/9#issuecomment-2297873952)for that review

**Comment by Lind111** [comment] 2024-09-27 08:32
checker:manualTrigger

**Comment by Lind111** [comment] 2024-10-02 05:52
checker:manualTrigger

**Comment by Lind111** [comment] 2024-10-02 05:56
> Number of replicas to store
> 11

The current copy number is 13, can you explain that?

**Comment by Brady168** [comment] 2024-10-09 06:18
> > Number of replicas to store
> > 11
> 
> The current copy number is 13, can you explain that?

Since this dataset is affected by the stfil event, I'm considering resealing their terminated data in as well, it could be that the original data is inaccurate which could cause me to misjudge the number of copies, so how do I do that?

**Closed** 2024-10-15 10:47 UTC
Labels: Refill needed
